export const METHOD_TYPES = {
  NORMAL: "NORMAL",
  BOUNDED: "BOUNDED",
  ADAPTIVE_BOUNDED: "ADAPTIVE_BOUNDED",
  SEQUENCE_ALIGNMENT: "SEQUENCE_ALIGNMENT",
};

export const COPY_DIRECTIONS = {
  TOP: "TOP",
  LEFT: "LEFT",
  DIAGONAL: "DIAGONAL",
  MATCH: "MATCH"
};
